// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNLPyQTpIvoQSLeSRkNptvWTEND1X3J7I',
    appId: '1:1076599407396:web:02fef083a3f1c2d827e9b1',
    messagingSenderId: '1076599407396',
    projectId: 'dr-scan-project',
    authDomain: 'dr-scan-project.firebaseapp.com',
    storageBucket: 'dr-scan-project.appspot.com',
    measurementId: 'G-B1LNYZ5M77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApf18ozO3Nx23drZU04evRMx8rEqyH7vQ',
    appId: '1:1076599407396:android:da6b1acc21b920a627e9b1',
    messagingSenderId: '1076599407396',
    projectId: 'dr-scan-project',
    storageBucket: 'dr-scan-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLa5LKo0bBCUuQqHqw8QkGwL_oTghDCf4',
    appId: '1:1076599407396:ios:9352f6c770cb770727e9b1',
    messagingSenderId: '1076599407396',
    projectId: 'dr-scan-project',
    storageBucket: 'dr-scan-project.appspot.com',
    iosClientId: '1076599407396-7me650oi63d06l2u373ravhcd2vksiph.apps.googleusercontent.com',
    iosBundleId: 'com.example.drScanGraduationProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLa5LKo0bBCUuQqHqw8QkGwL_oTghDCf4',
    appId: '1:1076599407396:ios:9352f6c770cb770727e9b1',
    messagingSenderId: '1076599407396',
    projectId: 'dr-scan-project',
    storageBucket: 'dr-scan-project.appspot.com',
    iosClientId: '1076599407396-7me650oi63d06l2u373ravhcd2vksiph.apps.googleusercontent.com',
    iosBundleId: 'com.example.drScanGraduationProject',
  );
}
